[font]
size = 12.0

[font.normal]
# family = "Monospace"
# family = "JetBrainsMono Nerd Font Mono"
family = "JetBrainsMono Emoji"
# family = "Noto Color Emoji"
style = "Medium"

[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xd19a66"

[colors.primary]
background = "0x2b303b"
foreground = "0xabb2bf"

[window]
opacity = 0.9

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
