general {
    # borders
    border_size = 1
    col.active_border = rgba(ffffffaa)
    col.inactive_border = rgba(2a2a2a80)

    # gaps
    gaps_in = 6
    gaps_out = 12
    gaps_workspaces = 50
}

decoration {
    rounding = 8
    blur {
        enabled = yes
        size = 8
        passes = 3
        ignore_opacity = on
        xray = false
    }

    shadow {
        enabled = yes
        range = 25
        render_power = 3
        color = rgba(00000044)
        color_inactive = rgba(00000022)
    }
}
