gestures {
    workspace_swipe_forever = true
    workspace_swipe_create_new = false
    workspace_swipe_direction_lock = false
}

gesture = 3, horizontal, workspace
gesture = 3, vertical, special, Obsidian
