env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = XKB_DEFAULT_LAYOUT,real-prog-dvorak # This is mostly for gamescope

source = ~/.config/hypr/hyprland.conf.d/*.conf

general {
    layout = dwindle
}

misc {
    vrr = false
    disable_hyprland_logo = true
    disable_splash_rendering = true
    enable_anr_dialog = false
}
